#:kivy 2.0.0

<RoundedButton>:
    btn_color_not_pressed: [.5, .5, .5, 1]
    btn_color_pressed: [.25, .25, .25, 1]

    background_color: (0,0,0,0)
	background_normal: ''
	canvas.before:
		Color:
            rgba: self.btn_color_not_pressed if self.state=='normal' else self.btn_color_pressed
		RoundedRectangle:
			size: self.size
			pos: self.pos
			radius: [20]


<StartScreen>:
    name: 'start'
    BoxLayout:
        orientation: 'vertical'
        padding: 50

        Label:
            text: 'Simple DCA'
            font_size: '80'

        BoxLayout:
            orientation: 'vertical'
            spacing: 40
            padding: root.width / 4, 20, root.width / 4, 20
            RoundedButton:
                text: 'Find Device'
                on_release: app.root.ids.sm.current = 'connection'
            RoundedButton:
                text: "Goodbye World!"
                on_release: print("Bye")


<SelectableLabelV1>:
    canvas.before:
        Color:
            rgba: .5, .5, .5, 1
        Line:
            width: 1
            rectangle: self.x, self.y, self.width, self.height

<SelectableLabelV2>:
    canvas.before:
        Color:
            rgba: (1, 0, 0, 1) if self.selected else (.0, 0.9, .1, .3)
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: (0, 0.9, .1, .3)
        Rectangle:
            pos: self.pos
            size: self.size

<ConnectionScreen>:
    name: 'connection'
    connections: connections_list
    AnchorLayout:
        padding: root.width / 5
        BoxLayout:
            id: group
            orientation: 'vertical'
            spacing: 0
            canvas.before:
                Color:
                    rgba: .5, .5, .5, 0.2
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [20]
            Label:
                text: 'Connections'
                height: self.texture_size[1]
                size_hint_y: None
                font_size: '50'
            RecycleView:
                id: connections_list
                viewclass: 'SelectableLabel'
                SelectableRecycleBoxLayout:
                    default_size: None, dp(26)
                    default_size_hint: 1, None
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: 'vertical'
                    multiselect: True
                    touch_multiselect: False


<DroneRoot>:
    MyScreenManager:
        id: sm
        StartScreen:
        ConnectionScreen:

